[project]
name = "memotic"
version = "0.2.3"
description = "A modern, async-first Python client for the Memos API, with Pydantic models and auto-generation from protobuf definitions."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "Bullish-Design", email = "BullishDesignEngineering@gmail.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "grpclib>=0.4.7",
    "pydantic>=2.7.0",
    "httpx>=0.27.0",
    "python-dotenv>=1.0.0",
    "betterproto2-compiler>=0.7.1", # NOTE: I fucked with the devenv compiler to remove ruff format check, need to figure out playing nice with nixos 
    "grpcio-tools>=1.74.0",
    "betterproto2[grpclib]>=0.7.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
    "uv>=0.1.0",
]

[project.scripts]
memotic-generate = "memotic.scripts.generate:main"

[project.urls]
Homepage = "https://github.com/Bullish-Design/memotic"
Repository = "https://github.com/Bullish-Design/memotic"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
exclude = [
  "/.github",
  "/.gitignore",
  #"/src/memotic/proto_gen", # Exclude generated code from source distribution
]

[tool.hatch.build.targets.wheel]
packages = ["src/memotic"]
