services:
  sandbox:
    # you can switch to the build block below if you prefer the Dockerfile
    image: debian:bookworm-slim
    container_name: memotic-cli-sandbox
    working_dir: /workspace
    command: ["bash", "-lc", "sleep infinity"]
    volumes:
      # from src/examples/cli-sandbox up to repo root is ../../../
      - ../../..:/workspace
    tty: true
    init: true
    restart: unless-stopped

    # If you want to build instead of pulling the image, comment "image:" above
    # and uncomment the block below, plus ensure the Dockerfile (next snippet) exists.
    # build:
    #   context: .
    #   dockerfile: Dockerfile
